BEGIN TRANSACTION;
DROP TABLE IF EXISTS `players`;
CREATE TABLE IF NOT EXISTS `players` (
	`ID`	INTEGER NOT NULL,
	`name`	TEXT,
	`score`	INTEGER,
	`games_played`	INTEGER,
	`provisional`	INTEGER
);
DROP TABLE IF EXISTS `games`;
CREATE TABLE IF NOT EXISTS `games` (
	`ID`	INTEGER NOT NULL,
	`WHITE`	INTEGER,
	`BLACK`	INTEGER,
	`result`	INTEGER,
	FOREIGN KEY(`BLACK`) REFERENCES `players`(`ID`),
	PRIMARY KEY(`ID`),
	FOREIGN KEY(`WHITE`) REFERENCES `players`(`ID`)
);
COMMIT;
